# -*- coding: utf-8 -*-
"""Q&Amodel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zXIglrWuNvqXVYz2PLPYT2KhZAUENYsD
"""

!pip install transformers
from transformers import pipeline
qa_pipeline = pipeline("question-answering")
context = """
         RAG (Retrieval Augmented Generation) is a method where an AI model first searches for relevant documents and then generates answers using the retrieved information.The explicit purpose of RAG is to ensure answers are more accurate and up-to-date.
         When a user submits a query,the system first engages the retrieval model, which specifically uses a vector database to identify and "retrieve" semantically similar documents,databases,etc for relevant information.
         Once identified,it then combines those results with the original input prompt and sends it to a generative AI model,which synthesizes the new information into its own model.

          """
question = [
    "What does RAG stand for ?",
    "What is the purpose of RAG ?",
    "What type of database does the retrieval model use ?"
          ]
result = qa_pipeline(question=question,context=context)
for q, r in zip(question, result):
    print(f"Question: {q}")
    print(f"Answer: {r['answer']}")
    print(f"Confidence score: {round(r['score'], 2)}")
    print("\n")